### ISSUE TITLE
Not Sublime Text 3 compliant (according to Package Control)

### ISSUE THREAD

**Issue by pyrrho** [FMCorz/MoveTab#3]
I'm not sure when the shift happened, but the package control channel now tracks which versions of Sublime Text any given package is compatible with. During the update, all packages were set to only be compatible with ST2 (as was the only reasonable choice), and it's on the package maintainers to mark their packages ST3 compliant, as per [wbond's example](https://github.com/wbond/sublime_package_control/blob/master/example-repository.json#L192-L205).
All this entails is forking [package control](https://github.com/wbond/sublime_package_control), and changing

[package_control_channel/repository/m.json](https://github.com/wbond/package_control_channel/blob/master/repository/m.json#L669):

```
    {
        "details": "https://github.com/SublimeText/MoveTab",
        "releases": [
            {
                "sublime_text": "<3000",
                "details": "https://github.com/SublimeText/MoveTab/tree/master"
            }
        ]
    },
```

to

```
    {
        "details": "https://github.com/SublimeText/MoveTab",
        "releases": [
            {
                "sublime_text": "*",
                "details": "https://github.com/SublimeText/MoveTab/tree/master"
            }
        ]
    },
```

---

I feel I should apologize for opening an issue in this repository that requests a change to another, but I'm not sure I want to set the precedent of making changes in the package control repo on account of someone else's plugin. The change is simple enough though, as you can see, and response times on this project seem pretty quick, so I'm hoping it's not a big deal. I'd also love to see MoveTab back in the package list to ST3.

Best,

**Comment by FMCorz** [comment]
No problem, I am actually surprised that this plugin is in the repository as I have never submitted it. I assume that this was done automatically from the group Sublime Text on Github. Thanks for the report anyway, I will try to fix that asap.

**Comment by FMCorz** [comment]
Thanks. Fixed upstream.

**Comment by pyrrho** [comment]
Beautiful. Thank you much.
