### ISSUE TITLE
An alternative shortcut for OS X

### ISSUE THREAD

**Issue by kdemidov** [FMCorz/MoveTab#4]
Probably it makes sense to change the default shortcuts like this:
`super+alt+shift+left` -> `super+alt+shift+[`
`super+alt+shift+right` -> `super+alt+shift+]`
It's very handy since `super+shift+[` and `super+shift+]`are used to switch to left/right tab, so by pressing the additional key `alt` it will be possible to move a current tab to the left/right.
What do you think?

**Comment by FMCorz** [comment]
Good idea, feel free to submit a pull request. If not, I'll try to get onto it soonish.

Thanks!

**Comment by FMCorz** [comment]
Actually, I just had a look and both are defaults to change tab on OSX:

```
    { "keys": ["super+shift+["], "command": "prev_view" },
    { "keys": ["super+shift+]"], "command": "next_view" },
    { "keys": ["super+alt+left"], "command": "prev_view" },
    { "keys": ["super+alt+right"], "command": "next_view" },
```

I could add both shortcuts to MoveTab but I don't really want to create conflicts with other plugins.

**Comment by kdemidov** [comment]
You're right. I've forgot about `super+alt+left` and `super+alt+right` because I don't use them :)
So, I agree that it makes sense to not modify/add new default shortcuts. Users can set their own key bindings if needed.

**Comment by FMCorz** [comment]
Thanks!
