### ISSUE TITLE
[Request] Behaviour compatibility with Chrome, Firefox, VSCode...

### ISSUE THREAD

**Issue by MrSnugglesGH** [FMCorz/MoveTab#9]
In chrome, firefox and vs code if you press and hold `ctrl + shift + page up/down` you move your tab to either the first or the last position and then the tab stops moving, even if you keep holding `ctrl + shift + page up/down`. In sublime text 4 however, your tab keeps circling around and never stops moving. It would be nice if the behaviour of this extension followed the same design principle as in the other apps mentioned above.

**Comment by FMCorz** [comment]
Hi @MrSnugglesGH,

Thanks for your request. I am no longer maintaining this plugin as I have moved on to VS Code. I recommend reporting this issue at the new repository: https://github.com/SublimeText/MoveTab

Thank you!
